# Generated by Django 6.0.2 on 2026-02-08 21:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('os', '0001_initial'),
        ('pessoas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcaoTecnica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
                ('data_hora', models.DateTimeField(default=django.utils.timezone.now)),
                ('ordem_servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acoes', to='os.ordemservico')),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='acoes', to='pessoas.profissional')),
            ],
            options={
                'verbose_name': 'Ação Técnica',
                'verbose_name_plural': 'Ações Técnicas',
            },
        ),
        migrations.CreateModel(
            name='FotoAcao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='acoes/')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('acao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='acoes.acaotecnica')),
            ],
            options={
                'verbose_name': 'Foto da Ação',
                'verbose_name_plural': 'Fotos da Ação',
            },
        ),
    ]
