# Generated by Django 6.0.2 on 2026-02-08 21:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('pessoas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdemServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, unique=True)),
                ('descricao', models.TextField(blank=True)),
                ('data_abertura', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_finalizacao', models.DateTimeField(blank=True, null=True)),
                ('tempo_total_minutos', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordens', to='core.statusos')),
            ],
            options={
                'verbose_name': 'Ordem de Serviço',
                'verbose_name_plural': 'Ordens de Serviço',
            },
        ),
        migrations.CreateModel(
            name='OrdemServicoProfissional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_atribuicao', models.DateTimeField(auto_now_add=True)),
                ('ordem_servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordem_profissionais', to='os.ordemservico')),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordem_profissionais', to='pessoas.profissional')),
            ],
            options={
                'verbose_name': 'Profissional da OS',
                'verbose_name_plural': 'Profissionais da OS',
                'unique_together': {('ordem_servico', 'profissional')},
            },
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='profissionais',
            field=models.ManyToManyField(related_name='ordens', through='os.OrdemServicoProfissional', to='pessoas.profissional'),
        ),
    ]
