# Generated by Django 6.0.2 on 2026-02-08 21:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profissional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('matricula', models.CharField(max_length=4, unique=True, validators=[django.core.validators.RegexValidator('^\\d{4}$', 'A matrícula deve ter 4 dígitos.')])),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Profissional',
                'verbose_name_plural': 'Profissionais',
            },
        ),
    ]
