# Generated by Django 6.0.2 on 2026-02-08 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StatusOS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
                ('descricao', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Status da OS',
                'verbose_name_plural': 'Status da OS',
            },
        ),
    ]
